name: Pull Request

on: [pull_request]
  
jobs:
  tests:
    name: Test LocalDrive
    runs-on: windows-latest

    steps:

      - name: Checkout Source Repository
        uses: actions/checkout@v2
      
      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build the Common Connector
        working-directory: 'sources/CloudDrive.Connector.Common/'
        run: msbuild -r -p:Configuration=Release
        
      - name: Build the LocalDrive Connector
        working-directory: 'sources/CloudDrive.Connector.LocalDrive/'
        run: msbuild -r -p:Configuration=Release
        
      - name: Build the LocalDrive Tester
        working-directory: 'tests/CloudDrive.Connector.LocalDriveTests/'
        run: msbuild -r -p:Configuration=Release 
        
      - name: Run the Tests
        working-directory: 'tests/CloudDrive.Connector.LocalDriveTests/'
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          