name: Pull Request

on: [pull_request]
  
jobs:
  tests:
    name: Test LocalDrive
    runs-on: windows-latest

    steps:

      - name: Checkout Source Repository
        uses: actions/checkout@v2
      
      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      # - name: Build the Common Connector
      #   working-directory: 'sources/CloudDrive.Connector.Common/'
      #   run: msbuild -r -p:Configuration=Release
        
      # - name: Build the LocalDrive Connector
      #   working-directory: 'sources/CloudDrive.Connector.LocalDrive/'
      #   run: msbuild -restore -p:Configuration=Debug -p:TargetFrameworks=netstandard2.0
        
      - name: Build the LocalDrive Tester
        working-directory: 'tests/CloudDrive.Connector.LocalDriveTests/'
        run: msbuild -restore -p:Configuration=Debug /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        
      - name: Run the Tests
        working-directory: 'tests/CloudDrive.Connector.LocalDriveTests/'
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Send report to codecov.io
        run: |
          curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          