name: Pull Request

on: [pull_request]
  
jobs:
  tests:
    name: Validate Changes
    runs-on: windows-latest

    steps:

      - name: Checkout Source Repository
        uses: actions/checkout@v2
      
      - name: Setup MsBuild Tooling
        uses: microsoft/setup-msbuild@v1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"          

      - name: Define Stable Release
        if: github.ref == 'refs/pull/68/merge'
        run: echo "::set-env name=suffixVersion::"
                    
      - name: Define Pre Release
        if: github.ref != 'refs/pull/68/merge'
        run: echo "::set-env name=suffixVersion::-alpha"
                    
      - name: Build the LocalDrive Test Project
        working-directory: 'tests/CloudDrive.Connector.LocalDriveTests/'
        run: msbuild -restore -p:Configuration=Debug /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:SuffixVersion=$suffixVersion
        
      - name: Run the LocalDrive Tests
        working-directory: 'tests/CloudDrive.Connector.LocalDriveTests/'
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:SuffixVersion=$suffixVersion

      - name: Build the OneDrive Test Project
        working-directory: 'tests/CloudDrive.Connector.OneDriveTests/'
        run: msbuild -restore -p:Configuration=Debug /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:SuffixVersion=$suffixVersion
        
      - name: Run the OneDrive Tests
        working-directory: 'tests/CloudDrive.Connector.OneDriveTests/'
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:SuffixVersion=$suffixVersion

      - name: Send Tests Report to Codecov.IO
        run: |
          curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          