name: Pull Request

on:
  pull_request:
    # branches: 
    #   - '*'
    #  - '!master'
  
jobs:
  build:
    name: Build Packages
    runs-on: windows-latest

    steps:
    
      - name: Checkout Source Repository
        uses: actions/checkout@v2
      
      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1
        
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"          
                    
      - name: Build the Common Connector
        run: msbuild ./sources/CloudDrive.Connector.Common -r -p:Configuration=Release /p:BuildVersion=${{ github.run_number }} /p:SuffixVersion=-alpha
          
      - name: Build the OneDrive Connector
        run: msbuild ./sources/CloudDrive.Connector.OneDrive -r -p:Configuration=Release /p:BuildVersion=${{ github.run_number }} /p:SuffixVersion=-alpha
          
      - name: Build the LocalDrive Connector
        run: msbuild ./sources/CloudDrive.Connector.LocalDrive -r -p:Configuration=Release /p:BuildVersion=${{ github.run_number }} /p:SuffixVersion=-alpha
          